### ISSUE TITLE
Model Visualization giving error.

### ISSUE THREAD

**Issue by adhishthite** [Prodicode/ann-visualizer#11]
Hello,

Here is the code for which I am trying to use ANN Visualizer-

```python
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D, BatchNormalization

from ann_visualizer.visualize import ann_viz;

def get_cnn_model(input_shape, num_classes):
    model = Sequential()

    model.add(Conv2D(32, kernel_size=(2, 2), activation='relu', input_shape=input_shape))
    model.add(BatchNormalization())

    model.add(Conv2D(48, kernel_size=(2, 2), activation='relu'))
    model.add(BatchNormalization())

    model.add(Conv2D(120, kernel_size=(2, 2), activation='relu'))
    model.add(BatchNormalization())

    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())

    model.add(Dense(128, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.25))
    model.add(Dense(64, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.4))
    model.add(Dense(num_classes, activation='softmax'))
    model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adadelta(), metrics=['accuracy'])

    ann_viz(model, title="Neural Network Model", filename='../images/model.gv')

    return model


if __name__ == '__main__':
model = get_cnn_model((20, 20, 1), 10)
print(model.summary())
```

However, when I run this code, I get the following error from ANN-Viz -

```
Traceback (most recent call last):
  File "/Users/adhishthite/PycharmProjects/soundMNIST/utils/model.py", line 39, in <module>
    model = get_cnn_model((20, 20, 1), 10)
  File "/Users/adhishthite/PycharmProjects/soundMNIST/utils/model.py", line 33, in get_cnn_model
    ann_viz(model, title="Neural Network Model", filename='../images/model.gv')
  File "/Users/adhishthite/anaconda/envs/tfdeeplearning/lib/python3.5/site-packages/ann_visualizer/visualize.py", line 126, in ann_viz
    if (layer_types[i] == "Dense"):
IndexError: list index out of range
```

Can you kindly fix this issue?

**Comment by saladedefruit** [comment]
Same issue here

**Comment by thomaspheiffer** [comment]
In my case I discovered the issue is because I have some layer types which are not handled (i.e. `BatchNormalization`). The solution to this issue seems to be to add the remaining Keras layer types to the proper `if` statements.

**Comment by Prodicode** [comment]
@thomaspheiffer That is exactly what I wanted to answer. It should have had correctly handled the exception, but it didn't. Atleast we know what the problem was and I will try to add more keras layers soon. You are free to open a pull request if you want to help with this and add other layers.

**Comment by veedhee** [comment]
Hello, I've encountered the same issue. Just wanted to know if the issue has been resolved and it's a fault on my end. Thank you.
