### ISSUE TITLE
runing ann-visualizer, Error

### ISSUE THREAD

**Issue by issxjl2015** [Prodicode/ann-visualizer#6]
I want to visualizer about YOLO v2, but runing the ann-visualizer, Error.
enviorment: ubuntu 16.10, python3.6, tensorflow1.3.0, Keras2.0.5
Look forward to your reply!

python yolov2_Visualizer.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/tianao/anaconda3/lib/python3.6/site-packages/graphviz/backend.py", line 124, in render
    subprocess.check_call(args, startupinfo=STARTUPINFO, stderr=stderr)
  File "/home/tianao/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/tianao/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/tianao/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/tianao/anaconda3/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yolov2_Visualizer.py", line 25, in <module>
    ann_viz(network, title=""); File "/home/tianao/anaconda3/lib/python3.6/site-packages/ann_visualizer/visualize.py", line 204, in ann_viz
    g.view();
  File "/home/tianao/anaconda3/lib/python3.6/site-packages/graphviz/files.py", line 203, in view
    cleanup=cleanup)
  File "/home/tianao/anaconda3/lib/python3.6/site-packages/graphviz/files.py", line 176, in render
    rendered = backend.render(self._engine, self._format, filepath)
  File "/home/tianao/anaconda3/lib/python3.6/site-packages/graphviz/backend.py", line 127, in render
    raise ExecutableNotFound(args)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Tpdf', '-O', 'network.gv'], make sure the Graphviz executables are on your systems' PATH

**Comment by Prodicode** [comment]
It seems like graphviz is not installed on your system. Can you double-check the installation of graphviz?

**Comment by Prodicode** [comment]
Use

```bash
sudo apt-get install graphviz
```

to install graphviz

**Comment by tobiaspiechowiak** [comment]
I have the same problem... but I have graphviz installed on the system and I also set the system path.
Any idea?
