### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by adeyris** [Prodicode/ann-visualizer#7]
Hi ! Thanks for this contribution :)

I'm trying to run ann-visualizer on keras-RetinaNet, but I get this error : 

ValueError: invalid literal for int() with base 10: 'Non'

Any idea of how to solve it ?

**Comment by Prodicode** [comment]
Can you provide a code sample?

**Comment by Prodicode** [comment]
It seems like keras-RetinaNet uses a DenseNet object to build the network. Our library only supports Sequential objects at this time.

**Comment by Prodicode** [comment]
@ZZHAOatEESI Are you passing the ann_viz() function a Model or a Sequential object?

**Comment by ZZHAOatEESI** [comment]
I passed a model object

On Apr 24, 2018, at 3:53 PM, Tudor Gheorghiu <notifications@github.com<mailto:notifications@github.com>> wrote:


@ZZHAOatEESI<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FZZHAOatEESI&data=02%7C01%7Czz374%40drexel.edu%7C139c5922b698493b096d08d5aa1d09ae%7C3664e6fa47bd45a696708c4f080f8ca6%7C0%7C0%7C636601964055275819&sdata=r2oaATx5HHnFx9GresQgg6O6RSTj9i19qXwyYcEqGF8%3D&reserved=0> Are you passing the ann_viz() function a Model or a Sequential object?

**Comment by Prodicode** [comment]
@shivam-deepcompute Can you provide the piece of code where you build the keras Sequential model? (Layer by layer)

**Comment by shivam-deepcompute** [comment]
@Prodicode 
```
def _create_base_network(self, input_dim):
    a = 'softsign'
    network = Sequential()
    network.add(Dense(1000, input_shape=(input_dim,), activation=a)
    network.add(Dense(150, input_shape=(input_dim,), activation=a))
    network.add(Dense(250, input_shape=(input_dim,), activation=a))
    network.add(Dense(300, input_shape=(input_dim,), activation='sigmoid')
    return network
```
This is my base sequential network, which accepts two inputs, as mentioned in the model summary.

**Comment by thpatty** [comment]
hello, i use your example , but i met this error below, can you help me ? 
i use windows 10 and jupyter notebook.  i can see the two files in the same file directory with *.ipynb
thanks firstly.


OSError: [WinError -2147221003] Application not found: 'network.gv.pdf'



import keras;
from keras.models import Sequential;
from keras.layers import Conv2D, Dense, Dropout, MaxPooling2D, Flatten;
from ann_visualizer.visualize import ann_viz

def build_cnn_model():
  model = keras.models.Sequential()

  model.add(
      Conv2D(
          32, (3, 3),
          padding="same",
          input_shape=(32, 32, 3),
          activation="relu"))
  model.add(Dropout(0.2))

  model.add(
      Conv2D(
          32, (3, 3),
          padding="same",
          input_shape=(32, 32, 3),
          activation="relu"))
  model.add(MaxPooling2D(pool_size=(2, 2)))
  model.add(Dropout(0.2))

  model.add(
      Conv2D(
          64, (3, 3),
          padding="same",
          input_shape=(32, 32, 3),
          activation="relu"))
  model.add(Dropout(0.2))

  model.add(
      Conv2D(
          64, (3, 3),
          padding="same",
          input_shape=(32, 32, 3),
          activation="relu"))
  model.add(MaxPooling2D(pool_size=(2, 2)))
  model.add(Dropout(0.2))

  model.add(Flatten())
  model.add(Dense(512, activation="relu"))
  model.add(Dropout(0.2))

  model.add(Dense(10, activation="softmax"))

  return model

model = build_cnn_model()
ann_viz(model, title="")

**Comment by LeandroRitter** [comment]
Hi!

I am using ANN Visualizer to display concatenated/merged layers but get errors, could you direct me how to properly visualize concatenated layers? Here is my code:

import keras;
from keras.models import Sequential;
from keras.layers import Dense, Concatenate, Merge;

network = Sequential();
network.add(Dense(units=6,
                  activation='relu',
                  kernel_initializer='uniform',
                  input_dim=11));

network.add(Dense(units=6,
                  activation='relu',
                  kernel_initializer='uniform'));

another_network = Sequential();
another_network.add(Dense(units=6,
                  activation='relu',
                  kernel_initializer='uniform',
                  input_dim=11));

#result = Sequential();
result = Merge([network, another_network], mode='concat')

#result.add(Dense(units=1,
#                  activation='sigmoid',
#                  kernel_initializer='uniform'));

from ann_visualizer.visualize import ann_viz;

ann_viz(result, title = "", view = True);

and here is the error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-c25a55adacd6> in <module>()
     28 from ann_visualizer.visualize import ann_viz;
     29 
---> 30 ann_viz(result, title = "Autoencoder", view = True);
     31 #convert -density 200 network.gv.pdf network.gv.png

~/miniconda3/lib/python3.6/site-packages/ann_visualizer/visualize.py in ann_viz(model, view, filename, title)
    121                 c.node(str(n), label="Image\n"+pxls[1]+" x"+pxls[2]+" pixels\n"+clrmap, fontcolor="white");
    122             else:
--> 123                 raise ValueError("ANN Visualizer: Layer not supported for visualizing");
    124         for i in range(0, hidden_layers_nr):
    125             with g.subgraph(name="cluster_"+str(i+1)) as c:

ValueError: ANN Visualizer: Layer not supported for visualizing

**Comment by endolith** [comment]
Same error:

```
model = Sequential([
    Dense(2, input_shape=(N, 2), use_bias=False)
    ])

ann_viz(model)
Traceback (most recent call last):

  File "<ipython-input-79-02a59322b308>", line 1, in <module>
    ann_viz(model)

  File "C:\Anaconda3\lib\site-packages\ann_visualizer\visualize.py", line 42, in ann_viz
    input_layer = int(str(layer.input_shape).split(",")[1][1:-1]);

ValueError: invalid literal for int() with base 10: ''
```

**Comment by smholsen** [comment]
I am also having the same issue with the following model. Do you know how to fix this? :)
```
            self.base_model = Sequential()
            self.base_model.add(Conv2D(20, input_shape=(5, 25, 1), kernel_size=(3, 3), strides=(1, 1), padding='same', activation='relu'))
            self.base_model.add(Flatten())
            self.base_model.add(Dropout(.4))
            self.base_model.add(Dense(1))
            # Compile model
            # self.base_model.summary()
            self.base_model.compile(loss='mse', optimizer='adam')
            self.base_model.fit(X1, y1, epochs=500, batch_size=128)
            ann_viz(self.base_model, title="ANN Topology")
```

```
  File "...\venv\lib\site-packages\ann_visualizer\visualize.py", line 42, in ann_viz
    input_layer = int(str(layer.input_shape).split(",")[1][1:-1]);
ValueError: invalid literal for int() with base 10: ''
```

**Comment by thpatty** [comment]
sorry, i cant kill this problem.

**Comment by Asrix-AI** [comment]
@shivam05011996 Did you get the solution?

**Comment by ShrikanthSingh** [comment]
```ValueError                                Traceback (most recent call last)
<ipython-input-271-6323c76e75d0> in <module>()
     16 # load weights into new model
     17 model.load_weights("model.h5")
---> 18 ann_viz(model, title="Artificial Neural network - Model Visualization")

/usr/local/lib/python3.6/dist-packages/ann_visualizer/visualize.py in ann_viz(model, view, filename, title)
     40     for layer in model.layers:
     41         if(layer == model.layers[0]):
---> 42             input_layer = int(str(layer.input_shape).split(",")[1][1:-1]);
     43             hidden_layers_nr += 1;
     44             if (type(layer) == keras.layers.core.Dense):

ValueError: invalid literal for int() with base 10: ''```
